### ISSUE TITLE
tdenginewriter写入从cassandra读入的json字符串失败

### ISSUE THREAD

**Issue by john1337** [taosdata/DataX#21]
相关错误日志如下：
ERROR convert nchar string to UCS4_LE failed:{"carNumber":"","image":"","outParkingSpace":1638927251000,"parkingSpaceStatus":0}
02/20 18:21:18.947000 00150464 TSC ERROR 0xf bind column 4: type mismatch or invalid
02/20 18:21:18.947000 00150464 JNI ERROR jobj:00000069469FE648, conn:000001CC512F7AA0, code:Invalid operation

**Comment by dingbo8128** [comment]
使用sql写入支持json字符串, 使用schemaless方式写入尚不支持json字符串。问题已经提交给数据库开发团队, 在后续发布的TDengine版本将会修复此问题。因此问题不是datax tdengie写插件造成的，可以在本仓库关闭此问题。
